version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2
  aws-cli: circleci/aws-cli@2.0.0
  aws-s3: circleci/aws-s3@1.0.9
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.4
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    executor: ruby/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - rubygems-v3-{{ checksum "Gemfile.lock" }}
            - rubygems-v3-fallback
      - run:
          name: Install current bundler version
          command: gem install bundler:$(tail -1 Gemfile.lock | tr -d " ")
      - run:
          name: Install Jekyll dependencies
          command: bundle check || bundle install --jobs 4
      - save_cache:
          key: rubygems-v3-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/repo/vendor/bundle
      - run:
          name: Build Jekyll Site
          command: bundle exec jekyll build
      - persist_to_workspace:
          root: ./
          paths:
            - _site
  deploy:
    docker:
      - image: cimg/python:3.9.1
    environment:
      S3_BUCKET_NAME: escalando-a-nuvem
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - attach_workspace:
          at: ./
      - run:
          name: Upload to s3
          command: aws s3 sync ./_site s3://$S3_BUCKET_NAME/ --delete
workflows:
  test-build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
